spring:
  datasource:
    url: jdbc://mysql://localhost:8080/employee_management_system?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update